- specifier: InputData
  title: Input Data
  description: >-
    The data used to drive the impact models, exactly as described in the ISIMIP simulation
    protocol.

- specifier: SecondaryInputData
  title: Secondary Input Data
  description: >-
    Data that have been derived from or are related to the input data, but not described
    in the simulation protocol (e.g. with a different spatial or temporal resolution).

- specifier: OutputData
  title: Output Data
  description: >-
    The climate-impacts simulation data provided by participating modelling groups,
    corresponding to the output variables described in the ISIMIP simulation protocol.

- specifier: SecondaryOutputData
  title: Secondary Output Data
  description: >-
    Data that have been derived by processing the ISIMIP output data, but do not correspond
    to output variables described in the simulation protocol.
