- specifier: InputData
  title: Input Data
  description: >-
    The data used to drive the impact models, exactly as described in the ISIMIP simulation
    protocol.

- specifier: SecondaryInputData
  title: Secondary Input Data
  description: >-
    Data similar to or related to the input data, but not described
    in the simulation protocol (e.g. with a different spatial or temporal resolution).

- specifier: DerivedInputData
  title: Derived Input Data
  description: >-
    Data derived from input data, typically for a specific publication.

- specifier: OutputData
  title: Output Data
  description: >-
    The climate-impacts simulation data provided by participating modelling groups,
    corresponding to the output variables described in the ISIMIP simulation protocol.

- specifier: SecondaryOutputData
  title: Secondary Output Data
  description: >-
    Data that have been calculated by participating modelling groups, but does not correspond
    to output variables described in the simulation protocol.

- specifier: DerivedOutputData
  title: Derived Output Data
  description: >-
    Data not directly simulated by the impact models themselves, but rather, calculated
    (post-processed) from the model's outputs, typically for a specific publication.
